language: cpp
dist: xenial
sudo: required
git:
  depth: 3
env:
  matrix:
    - PACKAGE='CHECK'
    - PACKAGE='AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations '
    - PACKAGE='Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres '
    - PACKAGE='Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 '
    - PACKAGE='Arithmetic_kernel Arrangement_on_surface_2 BGL '
    - PACKAGE='Barycentric_coordinates_2 Boolean_set_operations_2 Bounding_volumes '
    - PACKAGE='Box_intersection_d CGAL_Core CGAL_ImageIO '
    - PACKAGE='CGAL_ipelets Cartesian_kernel Circular_kernel_2 '
    - PACKAGE='Circular_kernel_3 Circulator Classification '
    - PACKAGE='Combinatorial_map Cone_spanners_2 Convex_decomposition_3 '
    - PACKAGE='Convex_hull_2 Convex_hull_3 Convex_hull_d '
    - PACKAGE='Distance_2 Distance_3 Envelope_2 '
    - PACKAGE='Envelope_3 Filtered_kernel Generalized_map '
    - PACKAGE='Generator Geomview GraphicsView '
    - PACKAGE='HalfedgeDS Hash_map Heat_method_3 '
    - PACKAGE='Homogeneous_kernel Hyperbolic_triangulation_2 Inscribed_areas '
    - PACKAGE='Installation Interpolation Intersections_2 '
    - PACKAGE='Intersections_3 Interval_skip_list Interval_support '
    - PACKAGE='Inventor Jet_fitting_3 Kernel_23 '
    - PACKAGE='Kernel_d LEDA Linear_cell_complex '
    - PACKAGE='MacOSX Maintenance Matrix_search '
    - PACKAGE='Mesh_2 Mesh_3 Mesher_level '
    - PACKAGE='Minkowski_sum_2 Minkowski_sum_3 Modifier '
    - PACKAGE='Modular_arithmetic Nef_2 Nef_3 '
    - PACKAGE='Nef_S2 NewKernel_d Number_types '
    - PACKAGE='OpenNL Optimal_transportation_reconstruction_2 Optimisation_basic '
    - PACKAGE='Partition_2 Periodic_2_triangulation_2 Periodic_3_mesh_3 '
    - PACKAGE='Periodic_3_triangulation_3 Periodic_4_hyperbolic_triangulation_2 Point_set_2 '
    - PACKAGE='Point_set_3 Point_set_processing_3 Poisson_surface_reconstruction_3 '
    - PACKAGE='Polygon Polygon_mesh_processing Polyhedron '
    - PACKAGE='Polyhedron_IO Polyline_simplification_2 Polynomial '
    - PACKAGE='Polytope_distance_d Principal_component_analysis Principal_component_analysis_LGPL '
    - PACKAGE='Profiling_tools Property_map QP_solver '
    - PACKAGE='Random_numbers Ridges_3 STL_Extension '
    - PACKAGE='Scale_space_reconstruction_3 Scripts SearchStructures '
    - PACKAGE='Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2 Set_movable_separability_2 '
    - PACKAGE='Shape_detection Skin_surface_3 Snap_rounding_2 '
    - PACKAGE='Solver_interface Spatial_searching Spatial_sorting '
    - PACKAGE='Straight_skeleton_2 Stream_lines_2 Stream_support '
    - PACKAGE='Subdivision_method_3 Surface_mesh Surface_mesh_approximation '
    - PACKAGE='Surface_mesh_deformation Surface_mesh_parameterization Surface_mesh_segmentation '
    - PACKAGE='Surface_mesh_shortest_path Surface_mesh_simplification Surface_mesh_skeletonization '
    - PACKAGE='Surface_mesher Surface_sweep_2 TDS_2 '
    - PACKAGE='TDS_3 Testsuite Three '
    - PACKAGE='Triangulation Triangulation_2 Triangulation_3 '
    - PACKAGE='Union_find Visibility_2 Voronoi_diagram_2 '
    - PACKAGE='wininst '
compiler: clang
install:
  - echo "$PWD"
  - if [ -n "$TRAVIS_PULL_REQUEST_BRANCH" ] && [ "$PACKAGE" != CHECK ]; then  DO_IGNORE=FALSE;  for ARG in $(echo "$PACKAGE");do if [ "$ARG" = "Maintenance" ]; then continue; fi; . $PWD/.travis/test_package.sh "$PWD" "$ARG";  echo "DO_IGNORE is $DO_IGNORE";  if [ "$DO_IGNORE" = "FALSE" ]; then  break; fi; done; if [ "$DO_IGNORE" = "TRUE" ]; then travis_terminate 0; fi;fi
  - /usr/bin/time -f 'Spend time of %C -- %E (real)' bash .travis/install.sh
  - export CXX=clang++ CC=clang;
before_script:
  - wget -O doxygen_exe https://cgal.geometryfactory.com/~mgimeno/doxygen_exe
  - sudo mv doxygen_exe /usr/bin/doxygen
  - sudo chmod +x /usr/bin/doxygen
  - mkdir -p build
  - cd build
  - /usr/bin/time -f 'Spend time of %C -- %E (real)' cmake -DCMAKE_CXX_FLAGS="-std=c++11" -DCGAL_HEADER_ONLY=ON -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG -DWITH_examples=ON -DWITH_demos=ON -DWITH_tests=ON ..
  - /usr/bin/time -f 'Spend time of %C -- %E (real)' make
  - /usr/bin/time -f 'Spend time of %C -- %E (real)' sudo make install &>/dev/null
  - cd ..
script:
  - cd ./.travis
  - /usr/bin/time -f 'Spend time of %C -- %E (real)' bash ./build_package.sh $PACKAGE
notifications:
  email:
    on_success: change
    # default: always
    on_failure: always
    # default: always
