language: cpp 
dist: trusty 
sudo: required 
git: 
 depth: 3
env:
 matrix: 
    - PACKAGE='CHECK' 
    - PACKAGE='AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations ' 
    - PACKAGE='Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres ' 
    - PACKAGE='Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 ' 
    - PACKAGE='Arithmetic_kernel Arrangement_on_surface_2 Barycentric_coordinates_2 ' 
    - PACKAGE='BGL Boolean_set_operations_2 Bounding_volumes ' 
    - PACKAGE='Box_intersection_d Cartesian_kernel CGAL_Core ' 
    - PACKAGE='CGAL_ImageIO CGAL_ipelets Circular_kernel_2 ' 
    - PACKAGE='Circular_kernel_3 Circulator Classification ' 
    - PACKAGE='Combinatorial_map Cone_spanners_2 Convex_decomposition_3 ' 
    - PACKAGE='Convex_hull_2 Convex_hull_3 Convex_hull_d ' 
    - PACKAGE='Distance_2 Distance_3 Envelope_2 ' 
    - PACKAGE='Envelope_3 Filtered_kernel Generalized_map ' 
    - PACKAGE='Generator Geomview GraphicsView ' 
    - PACKAGE='HalfedgeDS Hash_map Heat_method_3 ' 
    - PACKAGE='Homogeneous_kernel Inscribed_areas Installation ' 
    - PACKAGE='Interpolation Intersections_2 Intersections_3 ' 
    - PACKAGE='Interval_skip_list Interval_support Inventor ' 
    - PACKAGE='Jet_fitting_3 Kernel_23 Kernel_d ' 
    - PACKAGE='LEDA Linear_cell_complex MacOSX ' 
    - PACKAGE='Maintenance Matrix_search Mesh_2 ' 
    - PACKAGE='Mesh_3 Mesher_level Minkowski_sum_2 ' 
    - PACKAGE='Minkowski_sum_3 Modifier Modular_arithmetic ' 
    - PACKAGE='Nef_2 Nef_3 Nef_S2 ' 
    - PACKAGE='NewKernel_d Number_types OpenNL ' 
    - PACKAGE='Optimal_transportation_reconstruction_2 Optimisation_basic Partition_2 ' 
    - PACKAGE='Periodic_2_triangulation_2 Periodic_3_mesh_3 Periodic_3_triangulation_3 ' 
    - PACKAGE='Point_set_2 Point_set_3 Point_set_processing_3 ' 
    - PACKAGE='Point_set_shape_detection_3 Poisson_surface_reconstruction_3 Polygon ' 
    - PACKAGE='Polygon_mesh_processing Polyhedron Polyhedron_IO ' 
    - PACKAGE='Polyline_simplification_2 Polynomial Polytope_distance_d ' 
    - PACKAGE='Principal_component_analysis Principal_component_analysis_LGPL Profiling_tools ' 
    - PACKAGE='Property_map QP_solver Random_numbers ' 
    - PACKAGE='Ridges_3 Scale_space_reconstruction_3 Scripts ' 
    - PACKAGE='SearchStructures Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2 ' 
    - PACKAGE='Set_movable_separability_2 Skin_surface_3 Snap_rounding_2 ' 
    - PACKAGE='Solver_interface Spatial_searching Spatial_sorting ' 
    - PACKAGE='STL_Extension Straight_skeleton_2 Stream_lines_2 ' 
    - PACKAGE='Stream_support Subdivision_method_3 Surface_mesh ' 
    - PACKAGE='Surface_mesh_deformation Surface_mesher Surface_mesh_parameterization ' 
    - PACKAGE='Surface_mesh_segmentation Surface_mesh_shortest_path Surface_mesh_simplification ' 
    - PACKAGE='Surface_mesh_skeletonization Surface_sweep_2 TDS_2 ' 
    - PACKAGE='TDS_3 Testsuite Three ' 
    - PACKAGE='Triangulation Triangulation_2 Triangulation_3 ' 
    - PACKAGE='Union_find Visibility_2 Voronoi_diagram_2 ' 
    - PACKAGE='wininst ' 
compiler: clang-3.6
install: 
  - echo "$PWD"
  - if [ -n "$TRAVIS_PULL_REQUEST" ] && [ "$PACKAGE" != CHECK ]; then  DO_IGNORE=FALSE;  for ARG in $(echo "$PACKAGE");do if [ "$ARG" = "Maintenance" ]; then continue; fi; . $PWD/.travis/test_package.sh "$PWD" "$ARG";  echo "DO_IGNORE is $DO_IGNORE";  if [ "$DO_IGNORE" = "FALSE" ]; then  break; fi; done; if [ "$DO_IGNORE" = "TRUE" ]; then travis_terminate 0; fi;fi
  - bash .travis/install.sh 
  - export CXX=clang++-3.6 CC=clang-3.6;
before_script: 
- wget -O doxygen_exe https://cgal.geometryfactory.com/~mgimeno/doxygen_exe
- sudo mv doxygen_exe /usr/bin/doxygen
- sudo chmod +x /usr/bin/doxygen
- mkdir -p build 
- cd build 
- cmake -DCMAKE_CXX_FLAGS="-std=c++11" -DCGAL_HEADER_ONLY=ON -DQt5_DIR="/opt/qt55/lib/cmake/Qt5" -DQt5Svg_DIR="/opt/qt55/lib/cmake/Qt5Svg" -DQt5OpenGL_DIR="/opt/qt55/lib/cmake/Qt5OpenGL" -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG -DWITH_examples=ON -DWITH_demos=ON -DWITH_tests=ON .. 
- make 
- sudo make install &>/dev/null
- cd ..
script: 
- cd ./.travis
- bash ./build_package.sh $PACKAGE
notifications:
  email:
    on_success: change # default: always
    on_failure: always # default: always

