language: cpp 
dist: trusty 
sudo: required 
env: 
 matrix: 
  - PACKAGE='CHECK' 
  - PACKAGE='AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations ' 
  - PACKAGE='Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres ' 
  - PACKAGE='Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 ' 
  - PACKAGE='Arithmetic_kernel Arrangement_on_surface_2 Barycentric_coordinates_2 ' 
  - PACKAGE='BGL Boolean_set_operations_2 Bounding_volumes ' 
  - PACKAGE='Box_intersection_d Cartesian_kernel CGAL_Core ' 
  - PACKAGE='CGAL_ImageIO CGAL_ipelets Circular_kernel_2 ' 
  - PACKAGE='Circular_kernel_3 Circulator Classification ' 
  - PACKAGE='Combinatorial_map Cone_spanners_2 Convex_decomposition_3 ' 
  - PACKAGE='Convex_hull_2 Convex_hull_3 Convex_hull_d ' 
  - PACKAGE='Distance_2 Distance_3 Envelope_2 ' 
  - PACKAGE='Envelope_3 Filtered_kernel Generalized_map ' 
  - PACKAGE='Generator Geomview GraphicsView ' 
  - PACKAGE='HalfedgeDS Hash_map Homogeneous_kernel ' 
  - PACKAGE='Inscribed_areas Installation Interpolation ' 
  - PACKAGE='Intersections_2 Intersections_3 Interval_skip_list ' 
  - PACKAGE='Interval_support Inventor Jet_fitting_3 ' 
  - PACKAGE='Kernel_23 Kernel_d Kinetic_data_structures ' 
  - PACKAGE='Kinetic_framework LEDA Linear_cell_complex ' 
  - PACKAGE='MacOSX Maintenance Matrix_search ' 
  - PACKAGE='Mesh_2 Mesh_3 Mesher_level ' 
  - PACKAGE='Minkowski_sum_2 Minkowski_sum_3 Modifier ' 
  - PACKAGE='Modular_arithmetic Nef_2 Nef_3 ' 
  - PACKAGE='Nef_S2 NewKernel_d Number_types ' 
  - PACKAGE='OpenNL Operations_on_polyhedra Optimal_transportation_reconstruction_2 ' 
  - PACKAGE='Optimisation_basic Partition_2 Periodic_2_triangulation_2 ' 
  - PACKAGE='Periodic_3_triangulation_3 Point_set_2 Point_set_3 ' 
  - PACKAGE='Point_set_processing_3 Point_set_shape_detection_3 Poisson_surface_reconstruction_3 ' 
  - PACKAGE='Polygon Polygon_mesh_processing Polyhedron ' 
  - PACKAGE='Polyhedron_IO Polyline_simplification_2 Polynomial ' 
  - PACKAGE='Polytope_distance_d Principal_component_analysis Principal_component_analysis_LGPL ' 
  - PACKAGE='Profiling_tools Property_map QP_solver ' 
  - PACKAGE='Random_numbers Ridges_3 Scale_space_reconstruction_3 ' 
  - PACKAGE='Scripts SearchStructures Segment_Delaunay_graph_2 ' 
  - PACKAGE='Segment_Delaunay_graph_Linf_2 Set_movable_separability_2 Skin_surface_3 ' 
  - PACKAGE='Snap_rounding_2 Solver_interface Spatial_searching ' 
  - PACKAGE='Spatial_sorting STL_Extension Straight_skeleton_2 ' 
  - PACKAGE='Stream_lines_2 Stream_support Subdivision_method_3 ' 
  - PACKAGE='Surface_mesh Surface_mesh_deformation Surface_mesher ' 
  - PACKAGE='Surface_mesh_parameterization Surface_mesh_segmentation Surface_mesh_shortest_path ' 
  - PACKAGE='Surface_mesh_simplification Surface_mesh_skeletonization Surface_mesh_topology ' 
  - PACKAGE='Sweep_line_2 TDS_2 TDS_3 ' 
  - PACKAGE='Testsuite Three Triangulation ' 
  - PACKAGE='Triangulation_2 Triangulation_3 Union_find ' 
  - PACKAGE='Visibility_2 Voronoi_diagram_2 wininst ' 
  - PACKAGE='Polyhedron_demo' 
compiler: 
  - clang-3.6
  - gcc  
install: 
  - if [[ "$CXX" = "clang++" ]]; then export CXX=clang++-3.6 CC=clang-3.6; fi
before_script: 
- mkdir -p build 
- cd build 
- cmake -DCGAL_HEADER_ONLY=ON -DQt5_DIR="/opt/qt55/lib/cmake/Qt5" -DQt5Svg_DIR="/opt/qt55/lib/cmake/Qt5Svg" -DQt5OpenGL_DIR="/opt/qt55/lib/cmake/Qt5OpenGL" -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG .. 
- make 
- sudo make install
- cd .. 
script: 
- cd ./.travis
- bash -x -e ./build_package.sh $PACKAGE
addons: 
  apt:
    sources:
      - sourceline: 'ppa:ppsspp/cmake' 
      - sourceline: 'ppa:hedges/qt5.5'
    packages:
      - clang-3.6
      - zsh
      - cmake 
      - libboost1.55-dev 
      - libboost-system1.55-dev 
      - libboost-program-options1.55-dev 
      - libboost-thread1.55-dev 
      - libgmp-dev 
      - libmpfr-dev 
      - libmpfi-dev 
      - zlib1g-dev 
      - libeigen3-dev # too old 
      - qt55base
      - qt55script 
      - qt55svg
      - qt55tools
      - qt55graphicaleffects
       
      - mesa-common-dev
      - libglu1-mesa-dev
      # Not allowed (yet) 
      # - geomview 
      # - libglew1.5-dev 
      # - libipe-dev 
notifications:
  email:
    on_success: change # default: always
    on_failure: always # default: always
